### ISSUE TITLE
Error when trying to run E2P2

### ISSUE THREAD

**Issue by lpereira89** [carnegie/E2P2#17]
Hello,
I am trying to use E2P2 in a plant genome (_Alloteropsis semialata_). I found some errors when trying to run E2P2 and I am not sure about what the problem is (sorry - my bioinformatics experience is limited). I believe that I modified the config.init file correctly and the path to the input file is correct. I appreciate any advice - thank you in advance!

I paste the log file below:

`2024-08-12 15:11:55,165 e2p2            INFO     MainProcess Temp folder created at path /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902.
2024-08-12 15:11:55,166 e2p2            WARNING  MainProcess Log file /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902/e2p2.1723471902.log exists, will append to it...
2024-08-12 15:11:55,166 e2p2            INFO     MainProcess No user provided config.ini is found, attempting to use file at /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/config.ini.
2024-08-12 15:11:55,305 e2p2            INFO     MainProcess Missing 'blast_bit_score' in 'BLAST' section in config
2024-08-12 15:11:55,305 e2p2            WARNING  MainProcess BLAST Bit score in config missing or type error, using default 0.0.
2024-08-12 15:11:55,369 e2p2            INFO     MainProcess New process: BLAST: "blastp -db /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/blast/rpsd.v5.2.ef.fasta -num_threads 4 -query /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -out /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902/blast.AUS1_prot.1723471902.out -outfmt 6"
2024-08-12 15:11:55,369 e2p2            INFO     MainProcess New process: DEEPEC: "python /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec.py -i /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -o /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902"
2024-08-12 15:11:55,369 e2p2            INFO     MainProcess Running all available processes.
2024-08-12 15:11:55,371 e2p2            INFO     MainProcess Starting Process "blastp -db /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/blast/rpsd.v5.2.ef.fasta -num_threads 4 -query /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -out /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902/blast.AUS1_prot.1723471902.out -outfmt 6"
2024-08-12 15:11:55,372 e2p2            INFO     MainProcess Starting Process "python /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec.py -i /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -o /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902"
2024-08-12 15:11:56,074 e2p2            ERROR    MainProcess Process Error "blastp -db /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/blast/rpsd.v5.2.ef.fasta -num_threads 4 -query /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -out /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902/blast.AUS1_prot.1723471902.out -outfmt 6", stdout[0]: No such file or directory
2024-08-12 15:11:56,074 e2p2            ERROR    MainProcess Process Error "python /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec.py -i /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -o /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902", stdout[0]: Traceback (most recent call last):
2024-08-12 15:11:56,074 e2p2            ERROR    MainProcess Process Error "python /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec.py -i /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -o /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902", stdout[1]:   File "/mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec.py", line 5, in <module>
2024-08-12 15:11:56,074 e2p2            ERROR    MainProcess Process Error "python /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec.py -i /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -o /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902", stdout[2]:     from deepec.__main__ import main
2024-08-12 15:11:56,074 e2p2            ERROR    MainProcess Process Error "python /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec.py -i /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -o /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902", stdout[3]:   File "/mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec/__main__.py", line 9, in <module>
2024-08-12 15:11:56,074 e2p2            ERROR    MainProcess Process Error "python /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec.py -i /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -o /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902", stdout[4]:     from deepec import utils
2024-08-12 15:11:56,074 e2p2            ERROR    MainProcess Process Error "python /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec.py -i /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -o /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902", stdout[5]:   File "/mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec/utils.py", line 6, in <module>
2024-08-12 15:11:56,074 e2p2            ERROR    MainProcess Process Error "python /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec.py -i /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -o /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902", stdout[6]:     from Bio import SeqIO
2024-08-12 15:11:56,074 e2p2            ERROR    MainProcess Process Error "python /mnt/parscratch/users/bo1lpg/gene-cluster/E2P2/deepec/deepec.py -i /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.fa -o /mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902", stdout[7]: ModuleNotFoundError: No module named 'Bio'
2024-08-12 15:11:56,074 e2p2            INFO     MainProcess Reading blast output: "/mnt/parscratch/users/bo1lpg/gene-cluster/test/AUS1_prot.1723471902/blast.AUS1_prot.1723471902.out"`

**Comment by bxuecarnegie** [comment]
This seem to be caused by missing Python libraries required to run DeepEC. You can check the forked repo at https://github.com/bxuecarnegie/deepec and the dependencies listed in the [environment.yml](https://github.com/bxuecarnegie/deepec/blob/main/environment.yml) file.
