### ISSUE TITLE
Priam does not work anymore with java openjdk 11

### ISSUE THREAD

**Issue by lcottret** [carnegie/E2P2#2]
Java version on ubuntu 18.04:
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

With Java 11, priam returns this error:
### Individual sequence annotation ###
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: weka/core/Utils
        at priam.common.DistributionEstimator.<init>(DistributionEstimator.java:188)
        at priam.common.ProfInfos.setPositivesHitsDistrib(ProfInfos.java:229)
        at priam.common.AnnotationRulesXMLHandler2.startElement(AnnotationRulesXMLHandler2.java:133)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)

Resolved if I use java 8.

**Comment by bxuecarnegie** [comment]
Unfortunately, PRIAM isn't maintained by us. Please refer to their website http://priam.prabi.fr/

**Comment by lcottret** [comment]
I know but you should maybe add a warning in the README...

**Comment by bxuecarnegie** [comment]
Thanks for the catch, I'll update the README file
