### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by bjoernoest** [carnegie/E2P2#6]
Hi when running it with the following settings using python 3.7
python run_pipeline.py -i seqs.fa --blastp blastp --java java -ps ../PRIAM_search.jar --priam_profile ../data/profiles/ -r ../data/blastdb/rpsd-4.2.fasta

I get the following error, any idea why?

Process Process-2:
  File "/root/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Bioinf/E2P2/pipeline/prog.py", line 125, in worker_process
    call_output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'command': 'command'
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Bioinf/E2P2/pipeline/prog.py", line 125, in worker_process
    call_output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'command': 'command'

**Comment by lcottret** [comment]
Hi,
I think it corresponds to this pull request :
https://github.com/carnegie/E2P2/pull/1
Try by downloading the very last version since this pull request has been accepted.

**Comment by bjoernoest** [comment]
Oh my bad, It was on my todolist to ask for so long that it was fixed. Thank you

**Comment by bjoernoest** [comment]
Oh my bad, It was on my todolist to ask for so long that it was fixed. Thank you
